### ISSUE TITLE
Make client adapter based.

### ISSUE THREAD

**Issue by Hajto** [beno/xarango#10]
Different people like different HTTP clients, because they do have different properties. One of them leaked memory quite hard (don't know wether it was fixed).

I think it could be a good idea, to give people tool for changing those as they see fit.

i think that it would be good idea to make `behaviour` of Xarango http client and setup config for picking adapter.

If you think this is a good idea I can make it happen.

**Comment by beno** [comment]
If this is a requirement people have, it is certainly a good idea. Look forward to your PR!
