### ISSUE TITLE
Could this be made to work as the App.Repo?

### ISSUE THREAD

**Issue by fredevery** [beno/xarango#15]
In the same way that you config the database:
```
# Configure your database
config :app, App.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "app_dev",
  hostname: "localhost",
  pool_size: 10
```

Would it be possible to:
```
# Configure your database
config :app, App.Repo,
  adapter: Ecto.Adapters.Xarango,
  username: "arango",
  password: "arangopass",
  database: "app_dev",
  server: "http://localhost:8529",
  pool_size: 10
```

I found [this article](http://michal.muskala.eu/2015/07/07/creating-ecto-adapters.html) about writing ecto adapters and am happy to give it a bash, but would like to know if it is a viable task to undertake.

I would like to think that it would make it easier, and more accessible, to use arango as the repo db if the developer can interact with it in much the same way they use repo to perform CRUD operations against a sql db.

**Comment by pinx** [comment]
I made a start in https://github.com/pinx/arango but I would like to work on it together.
I took inspiration from the Redix driver, and from recent commits of the ArangoEx driver.
Especially https://github.com/austinsmorris/arangoex/blob/master/lib/arangoex/connection.ex

I think Arango is a bit different from relational databases, so complete support for Ecto should not be the goal.

Personally, I would like to have something that behaves like Ecto.Repo, so the code looks familiar, and Arango can be easily plugged in to replace Postgres.

**Comment by chintan-mishra** [comment]
https://github.com/hamiltop/rethinkdb-elixir
Maybe something like this for Arango where we manage connection pool and everything. Also, Xarango has brought most of the features of ArangoDB nicely to Elixir.

**Comment by pinx** [comment]
I'm not sure, but I think [VelocyPack](https://github.com/austinsmorris/velocy_pack) and [VelocyStream](https://github.com/austinsmorris/velocy_stream) are valuable to incorporate.
To be able to take advantage of [cursors](https://docs.arangodb.com/devel/HTTP/AqlQueryCursor/), we need a process per query.
I don't think Xarango supports all of these.
The Rethink driver looks great. It seems foreign from Ecto, at first sight, though.

**Comment by chintan-mishra** [comment]
RethinkDB driver is different from Ecto. I think it takes ideas from Ecto and beautifully transforms it into NoSQL domain.

@pinx I personally believe that Elixir community has a handful of ArangoDB users who are focussing their strengths in building various ArangoDB drivers. It'd be great if we can collaborate and focus on building one great library. Also, I couldn't agree more that VelocyPack and VelocyStream have grown into must-have features in ArangoDB driver's lib. I don't know anything about cursors but I will look into it.

If anyone is curious then here is the list of ArangoDB drivers in Elixir:
0: [Xarango](https://github.com/beno/xarango)
1: [Arango](https://github.com/pinx/arango)
2: [Arangox](https://github.com/timdunn22/arangox)
3. [Arango](https://github.com/edubkendo/arango) (Different from one mentioned above)
4. [Arangoex](https://github.com/austinsmorris/arangoex)
5. [Arangoex](https://github.com/ijcd/arangoex) (Different from one mentioned above)
6: [ArangoDBEcto](https://github.com/Lean5/arangodb_ecto)

**Comment by pinx** [comment]
@chintan-mishra, you say that a handful of ArangoDB users are focusing their strengths. From the list you presented, it looks more like several people are building their own solution ;)

It would be great to create a group of people, working on the same product. Maybe we can consider the libraries in your list as valuable experiments, learn from each of them, and create something that offers the best user/developer experience.

I have some connections with the ArangoDB company. I think if I ask them, they will create a repo for us under their organization. We could start the discussion there on how an Arango-Elixir driver would look like.

Would you be interested in contributing in this way? @fredevery ?

**Comment by chintan-mishra** [comment]
A report under ArangoDB will help us bring elixir driver in light

Btw I started a gitter channel for the same purpose check it out

https://gitter.im/Elixir-ArangoDB-Driver-Dev/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

Also, check your mail.

I'm more than willing to collaborate.

**Comment by fredevery** [comment]
@pinx I would love to be involved in any way I can. I have limited experience with Elixir, Ecto, and Phoenix (currently working on my first non-trivial project), but I do feel confident that I'll be able to be a productive contributor in a short period of time. 

I am very excited that this is turning into a proper investigation into the possibility of doing this. Of all the DBs I've looked at, SQL based, NoSQL based, and Graph, Arango has piqued my interest the most, and I've been sold on Phoenix/Elixir for a long while now. So if we can get a legit Arango driver going that would be amazing.

I was planning on suggesting that we formalise this conversation and prospective project a bit more with:

1. A project board (trello or something)
2. Move the conversation to the repo you started (but if Arango will give us a repo that'd be great too)
3. A slack channel in the Elixir slack group
4. Whatever other project management/productivity tools you can think of.

I've just opened @chintan-mishra's gitter link and looking into what that is after posting this, so apologies if my suggestions above are covered by gitter

**Comment by fredevery** [comment]
I am closing this issue as the discussion has moved to: https://gitter.im/Elixir-ArangoDB-Driver-Dev/Lobby
