### ISSUE TITLE
Transferring ownership

### ISSUE THREAD

**Issue by chintan-mishra** [beno/xarango#17]
At [8hoot](https://8hoot.com), we planned on supporting this library. However, due to certain limitation posed by the community edition, we pivoted to CouchDB. Before this move, we requested hex.pm to provide us rights to publish this package. And we will be releasing 0.7.0 for this package. After this release, no future updates will be provided by us.

As we have received the required permissions we'd be happy to facilitate the process of transferring ownership to anyone who'd like to build upon this library. You may also want to [look at the following package](https://gitlab.com/Rebhu_Computing/open-source/xarango) as it adds certain fix for failing tests and some goodies to get you started with Arango's 3.4.x.

**Comment by chintan-mishra** [comment]
I will close this issue once the publishing rights are transferred to someone looking to maintain the package or the original author [ @beno ] requests the same

**Comment by ijcd** [comment]
Hi. I'm interested in taking this over. I've been working on a lower-level driver and had been planning to add similar functionality to it. I'd rather just make the two work nicely together.

**Comment by chintan-mishra** [comment]
**I am curious** what do you mean by low-level?
Other than HTTP, and VelocyPack does ArangoDB allow any other option?

Also, I think we were in the same group related to Elixir+ArangoDB on Gitter. 

How about you private message me your email ID on Gitter and we can take it further from there?

What I can do is I can add you as a publisher on the Xarango package on [hex](https://hex.pm). Thereafter, you can build the project the way you want it.

I will close this issue when the transfer is complete.

**Comment by chintan-mishra** [comment]
The package has been transferred to @ijcd Please connect with them for any future release, maintenance, etc.

**Comment by norpan** [comment]
Hi.

I'm using xarango sucessfully for creating graphs and querying aql. I've made some improvements and additions for 3.4 (arangosearch views). Would you be interested in pull requests? Is this project live?

**Comment by ijcd** [comment]
Yes, definitely interested in PRs. The project is in transition, not dead!

--Ian
