### ISSUE TITLE
Differences between Node and Document

### ISSUE THREAD

**Issue by imetallica** [beno/xarango#5]
Hi! Thanks for the library!

I was browsing the code of your library and I couldn't figure out the reason why you treat `Nodes` and `Documents` differently since they are the same in ArangoDB. Any reason behind that?

Also, the lib could use some documentation. I could help with that, if you so wish.

Thanks,
I.

**Comment by beno** [comment]
Hi,

A Node is like a Vertex in the Domain namespace, intended to be part of a Graph, unlike a Document.
